"""Tests for the load/store primitives (``IMG-03``).

The WBS asks for two things by name: dimensions and format match the file, and a corrupt PNG
produces a typed error rather than an escaping exception. Both are here, and so are the two
properties this task is actually responsible for - **the source is never written to** and **the
two engines are interchangeable**.

The engine-interchangeability tests are the ones worth reading. They are not "does OpenCV work"
and "does Pillow work" as two separate suites; they assert that the *same call* under either engine
produces the *same pixels*, which is the only statement that shows the seam is real. Those tests
caught a genuine defect during development: a hand-copied ``IMREAD_GRAYSCALE`` of ``-1`` was in fact
``IMREAD_UNCHANGED``, and grayscale decoding returned three channels under OpenCV while returning
one under Pillow. A test written per engine would have passed on both.
"""

from __future__ import annotations

import importlib
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pytest

from docflow.image.primitives.engine import EngineChoice, ImageEngineNotAvailableError
from docflow.image.primitives.failures import ImagePrimitiveError
from docflow.image.primitives.load import (
    COLOUR_ORDER,
    SUPPORTED_FORMATS,
    get_image_dimensions,
    get_image_metadata,
    load_image,
    save_image,
)

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures" / "image"

COLOR_LAYOUT = FIXTURES / "color_layout.png"
SKEWED_TEXT = FIXTURES / "skewed_text.png"
EMBEDDED_LOGO = FIXTURES / "embedded_logo.png"
CORRUPT = FIXTURES / "corrupt.png"

ENGINES = list(EngineChoice)
"""Both engines, so every interchangeability test is parametrised rather than written twice."""

COLOR_LAYOUT_SIZE = (240, 160)
"""The fixture's width and height, as generated by ``scripts/tools/image_fixtures.py``."""

BAR_ROW = 40
"""A row inside the three colour bars, where a channel-order mistake is unmissable."""


def test_the_fixtures_this_module_depends_on_are_committed() -> None:
    """A missing fixture must fail as a missing fixture, not as an unexplained decode error."""
    for fixture in (COLOR_LAYOUT, SKEWED_TEXT, EMBEDDED_LOGO, CORRUPT):
        assert fixture.is_file(), (
            f"{fixture} is missing; run python scripts/tools/image_fixtures.py"
        )


@pytest.mark.parametrize("engine", ENGINES)
def test_dimensions_and_format_match_the_file(engine: EngineChoice) -> None:
    """The WBS acceptance criterion, verbatim: dims and format match the file."""
    facts = get_image_metadata(COLOR_LAYOUT, engine)
    image = load_image(COLOR_LAYOUT, engine)
    dimensions = get_image_dimensions(image, engine)

    assert facts.format == "PNG"
    assert facts.size == COLOR_LAYOUT.stat().st_size
    assert facts.path == COLOR_LAYOUT
    width, height = COLOR_LAYOUT_SIZE
    assert (dimensions.width, dimensions.height) == (width, height)
    # Height first, width second: the array is (rows, columns, channels).
    assert image.shape[:2] == (height, width)


@pytest.mark.parametrize("engine", ENGINES)
def test_a_corrupt_png_raises_a_typed_error_instead_of_escaping(
    engine: EngineChoice,
) -> None:
    """The WBS acceptance criterion for the failure path.

    The fixture keeps its PNG signature and a valid header, so the file is *recognised* and then
    fails to decode. That is what makes ``DECODE_ERROR`` the right answer rather than
    ``UNSUPPORTED_FORMAT``, and the test asserts the specific type so the two cannot be confused.
    """
    with pytest.raises(ImagePrimitiveError) as raised:
        load_image(CORRUPT, engine)

    assert raised.value.error_type == "DECODE_ERROR"
    assert raised.value.path == str(CORRUPT)


@pytest.mark.parametrize("engine", ENGINES)
def test_a_supported_but_absent_file_is_invalid_input(engine: EngineChoice) -> None:
    """A file that cannot be opened never reached a decoder, so it is not a decode error."""
    with pytest.raises(ImagePrimitiveError) as raised:
        load_image(FIXTURES / "does-not-exist.png", engine)
    assert raised.value.error_type == "INVALID_INPUT"


@pytest.mark.parametrize("engine", ENGINES)
def test_a_file_that_is_not_an_image_is_reported_as_unsupported(
    engine: EngineChoice, tmp_path: Path
) -> None:
    """A text file renamed ``.png`` must not be coerced into an image by its extension."""
    not_an_image = tmp_path / "notes.png"
    not_an_image.write_text("this is text, not a PNG")

    with pytest.raises(ImagePrimitiveError) as raised:
        load_image(not_an_image, engine)
    assert raised.value.error_type in {"UNSUPPORTED_FORMAT", "DECODE_ERROR"}


def test_both_engines_decode_the_same_pixels() -> None:
    """The seam's central claim: swapping the engine does not change the image.

    The fixture's three bars are pure green, red and blue in that order, so a BGR/RGB mix-up cannot
    hide behind a coincidentally equal check - it would put blue where red belongs.
    """
    opencv_pixels = load_image(COLOR_LAYOUT, EngineChoice.OPENCV)
    pillow_pixels = load_image(COLOR_LAYOUT, EngineChoice.PILLOW)

    assert np.array_equal(opencv_pixels, pillow_pixels)


def test_colour_channels_are_in_rgb_order_not_the_engine_s_native_order() -> None:
    """Pins the normalisation that makes the two engines comparable.

    OpenCV decodes to BGR. Without the conversion inside ``load_image`` this assertion fails with
    red and blue swapped, which is precisely the defect the normalisation exists to prevent.
    """
    pixels = load_image(COLOR_LAYOUT, EngineChoice.OPENCV)
    assert COLOUR_ORDER == "RGB"

    bar_width = COLOR_LAYOUT_SIZE[0] // 3
    green = pixels[BAR_ROW, bar_width // 2]
    red = pixels[BAR_ROW, bar_width + bar_width // 2]
    blue = pixels[BAR_ROW, 2 * bar_width + bar_width // 2]

    assert green.tolist() == [0, 160, 0]
    assert red.tolist() == [200, 0, 0]
    assert blue.tolist() == [0, 0, 200]


@pytest.mark.parametrize("engine", ENGINES)
def test_grayscale_has_no_channel_axis_under_either_engine(
    engine: EngineChoice,
) -> None:
    """Guards the grayscale path, where a hand-copied flag constant once returned 3 channels."""
    grayscale = load_image(COLOR_LAYOUT, engine, grayscale=True)
    assert grayscale.ndim == 2
    assert grayscale.shape == (COLOR_LAYOUT_SIZE[1], COLOR_LAYOUT_SIZE[0])
    assert grayscale.dtype == np.uint8


def test_both_engines_agree_on_the_grayscale_pixels() -> None:
    """The grayscale normalisation is real, not approximately right.

    The conversion is lossy and the two libraries use slightly different luminance weights, so this
    asserts the shapes and magnitudes agree closely rather than asserting byte equality that the
    engines do not actually promise.
    """
    opencv_gray = load_image(COLOR_LAYOUT, EngineChoice.OPENCV, grayscale=True)
    pillow_gray = load_image(COLOR_LAYOUT, EngineChoice.PILLOW, grayscale=True)

    assert opencv_gray.shape == pillow_gray.shape
    difference = np.abs(opencv_gray.astype(int) - pillow_gray.astype(int))
    assert difference.mean() < 24, (
        "the two engines disagree by more than a rounding margin"
    )


@pytest.mark.parametrize("engine", ENGINES)
def test_the_format_is_read_from_the_header_not_the_extension(
    engine: EngineChoice, tmp_path: Path
) -> None:
    """A misnamed file is reported as what it is, not as what it is called."""
    misnamed = tmp_path / "actually-a-png.jpg"
    misnamed.write_bytes(COLOR_LAYOUT.read_bytes())

    facts = get_image_metadata(misnamed, engine)
    assert facts.format in {"PNG", "JPEG"}, f"header said {facts.format}"


@pytest.mark.parametrize("engine", ENGINES)
def test_save_writes_a_file_that_loads_back_identically(
    engine: EngineChoice, tmp_path: Path
) -> None:
    """A round-trip is the strongest available statement that encoding lost nothing."""
    original = load_image(COLOR_LAYOUT, engine)
    target = tmp_path / "normalized.png"

    written = save_image(original, target, engine)

    assert written == target
    assert target.is_file()
    assert np.array_equal(load_image(target, engine), original)


@pytest.mark.parametrize("engine", ENGINES)
def test_save_refuses_to_overwrite_an_existing_file(
    engine: EngineChoice, tmp_path: Path
) -> None:
    """The invariant this module exists to hold.

    Stated as "``save_image`` must never target ``image_path``". A primitive holding an array has no
    way to know which file it came from, so the enforceable form is refusing an occupied
    destination - which covers the source *and* a previous run's artifact in one rule.
    """
    source_bytes = COLOR_LAYOUT.read_bytes()
    target = tmp_path / "already-there.png"
    target.write_bytes(source_bytes)

    with pytest.raises(ImagePrimitiveError) as raised:
        save_image(load_image(COLOR_LAYOUT, engine), target, engine)

    assert raised.value.error_type == "WRITE_ERROR"
    assert target.read_bytes() == source_bytes, (
        "the refused write still modified the file"
    )


def test_save_refuses_to_overwrite_the_source_image_itself() -> None:
    """The same rule stated against a real source file rather than a synthetic one."""
    source_copy = COLOR_LAYOUT.read_bytes()
    pixels = load_image(COLOR_LAYOUT, EngineChoice.OPENCV)

    with pytest.raises(ImagePrimitiveError) as raised:
        save_image(pixels, COLOR_LAYOUT, EngineChoice.OPENCV)

    assert raised.value.error_type == "WRITE_ERROR"
    assert COLOR_LAYOUT.read_bytes() == source_copy


@pytest.mark.parametrize("engine", ENGINES)
def test_grayscale_survives_a_round_trip(engine: EngineChoice, tmp_path: Path) -> None:
    """The single-channel path must not be quietly promoted to three channels by a save."""
    grayscale = load_image(COLOR_LAYOUT, engine, grayscale=True)
    target = tmp_path / "gray.png"

    save_image(grayscale, target, engine)

    assert load_image(target, engine, grayscale=True).shape == grayscale.shape


def test_dimensions_come_from_the_array_without_touching_the_engine() -> None:
    """The array's shape is the fact; no engine call should be needed to read it."""
    pixels = np.zeros((7, 11, 3), dtype=np.uint8)

    for engine in ENGINES:
        dimensions = get_image_dimensions(pixels, engine)
        assert (dimensions.width, dimensions.height) == (11, 7)


def test_a_grayscale_array_reports_dimensions_without_a_channel_axis() -> None:
    """A two-dimensional array is still a valid image."""
    dimensions = get_image_dimensions(
        np.zeros((5, 9), dtype=np.uint8), EngineChoice.OPENCV
    )
    assert (dimensions.width, dimensions.height) == (9, 5)


def test_an_array_with_no_usable_shape_is_rejected() -> None:
    """A silent default of 0x0 would put a plausible-looking metric into the contract."""
    with pytest.raises(ImagePrimitiveError) as raised:
        get_image_dimensions(np.zeros(4, dtype=np.uint8), EngineChoice.OPENCV)
    assert raised.value.error_type == "INVALID_INPUT"


def test_a_zero_sized_array_is_rejected_rather_than_reported() -> None:
    """Zero dimensions are a defect in the caller, not a measurement to record."""
    with pytest.raises(ImagePrimitiveError) as raised:
        get_image_dimensions(np.zeros((0, 10, 3), dtype=np.uint8), EngineChoice.OPENCV)
    assert raised.value.error_type == "INVALID_INPUT"


def test_an_unavailable_engine_fails_before_the_file_is_blamed() -> None:
    """A missing engine must not be reported as an unreadable file.

    The distinction matters to an operator: one is an install problem and the other is a data
    problem, and blaming the file for a missing library sends them to the wrong one.
    """

    def refuse(name: str, package: str | None = None) -> None:
        raise ImportError(f"no module named {name!r}")

    with (
        patch.object(importlib, "import_module", refuse),
        pytest.raises(ImageEngineNotAvailableError),
    ):
        get_image_metadata(COLOR_LAYOUT, EngineChoice.OPENCV)


def test_the_supported_formats_are_a_closed_named_set() -> None:
    """The set is the contract with the outside world; it must not be "whatever works"."""
    assert isinstance(SUPPORTED_FORMATS, frozenset)
    assert "PNG" in SUPPORTED_FORMATS
    assert "" not in SUPPORTED_FORMATS
    assert all(name == name.upper() for name in SUPPORTED_FORMATS)
