"""Build ``manifest.json``: a basic inventory of the committed fixture files.

Basic data only — path, folder, name, extension, size and content hash, all read
from the filesystem with the standard library. Nothing else is measured *about*
the bytes: a manifest that costs more to regenerate than to read is a manifest
nobody regenerates.

The one exception is a PDF's **type**. A fixture's extension says nothing about
whether a PDF holds text or is a scan, and that is the first question anything
aimed at these documents has to answer. So each PDF also records
``pdf_type`` — ``pdf_texto`` when the pages carry a text layer, ``pdf_escaneado``
when they do not — as decided by ``voucherflow``'s input-type detector
(``type_detector.detectar``), the legacy PoC's own answer rather than a
reimplementation of it. The values are that detector's vocabulary verbatim, and
its ``motivo`` prose is deliberately **not** recorded: a message string drifts,
and the repo's rule is that assertions target codes, never messages.

The detector is used **only when ``voucherflow`` is importable**. It is a legacy
package, it is not declared in ``pyproject.toml``, and ``legacy/`` is
git-ignored, so a fresh clone will not have it. Without it ``pdf_type`` is
**absent** rather than filled with a guess — a stand-in is worse than an
absence, and ``test_manifest.py`` asserts the difference instead of letting a
missing key read as a missing fact.

Two kinds of file are left out, and the difference matters:

- **Deliberate non-fixtures** — the Python sources in this folder: this script
  and its test — are *recorded* in ``excluded``, so the inventory plus the
  exclusion list accounts for the whole folder.
- **Debris** — cache directories, hidden/OS entries, and this script's own
  output — is *skipped without a record*. It appears and disappears on its own,
  so recording it would make the manifest differ between two runs and between a
  macOS and a Linux checkout. A manifest that flickers is not a check.

The output is deterministic: the same fixtures produce a byte-identical file.
Nothing that changes on its own — a timestamp, a tool version, an mtime, a
directory-iteration order — is recorded, so regenerate-and-diff is a usable
check, which is what ``test_manifest.py`` does.

Anything left over in the folder is a fixture by definition. If that is wrong,
the folder has the wrong thing in it, and the manifest is where it shows up.

This is an **inventory, not a golden set**: it records no expected content.
``docs/plans/README.md`` §6 defers the labelled golden set over deviation D4 (a
set labelled by the model that produced it is circular), so this file is
verified material and nothing more.

Run from the repository root::

    python tests/fixtures/build_manifest.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import pathlib
from collections.abc import Callable
from typing import Any, TypedDict

#: Suffixes left out of the inventory, mapped to the reason recorded for them.
#: Excluding by *rule* rather than by name: a list of names is forgotten the
#: moment a new generator is dropped next to the fixtures it produces.
EXCLUDED_SUFFIXES: dict[str, str] = {".py": "python_source"}

#: Directory names skipped whole, and the reason. Two kinds, and the difference is
#: whether the directory holds fixtures at all:
#:
#: - ``matrix/`` is the silent-failure harness's own input set (`E07-03` / `S1-T22`):
#:   the documents the 17-row matrix provokes its failures with, generated by
#:   ``matrix/build.py``. They are committed for the same reason a corpus fixture is -
#:   a test needs bytes - but they are **not** corpus fixtures, so neither a record nor
#:   an ``excluded`` entry would be true of them. Decided in ``_scan`` before any
#:   per-file rule.
#: - ``__pycache__`` is skipped without a record: a cache is not a claim about the
#:   fixtures.
EXCLUDED_DIRECTORIES: dict[str, str] = {
    "matrix": "silent_failure_fixtures",
    "__pycache__": "cache",
}

#: Bytes read per chunk while hashing. The fixtures include 4 MB photographs, so
#: the digest is computed in chunks rather than by reading whole files.
_CHUNK_BYTES = 1 << 20

#: The one extension that carries a type.
_PDF_SUFFIX = ".pdf"

#: The two answers the detector gives for a PDF, taken from ``voucherflow``
#: (``type_detector.TIPOS_VALIDOS``) rather than re-spelled here. A third value
#: would mean the detector answered about something other than a PDF, which is a
#: broken assumption rather than a new type.
PDF_TYPES: tuple[str, ...] = ("pdf_texto", "pdf_escaneado")

#: The detector, named once so the recorded provenance and the import agree.
_DETECTOR = "voucherflow"

_HERE = pathlib.Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parents[1]


class FixtureRecord(TypedDict, total=False):
    """One inventoried fixture file.

    ``total=False`` because ``pdf_type`` is present only for PDFs and only when
    the detector is importable. Both absences are meaningful, and
    ``test_manifest.py`` asserts them rather than letting a missing key read as a
    missing fact.
    """

    path: str
    folder: str
    name: str
    extension: str
    bytes: int
    sha256: str
    pdf_type: str


class ExcludedPath(TypedDict):
    """One deliberate non-fixture left out of the inventory."""

    path: str
    reason: str


class Manifest(TypedDict):
    """The inventory written to ``manifest.json``."""

    root: str
    files: int
    bytes: int
    pdf_detector: str
    by_folder: dict[str, dict[str, int]]
    excluded: list[ExcludedPath]
    entries: list[FixtureRecord]


def _exclusion_reason(path: pathlib.Path, root: pathlib.Path) -> str | None:
    """Return why ``path`` is not a fixture, or ``None`` if it is one.

    The order is load-bearing. Containment in a cache directory is decided
    before the suffix rule, because the two rules overlap: a Python file inside
    ``__pycache__`` matches both, and answering ``python_source`` would be a
    claim about what the file *is*, made about a file in a cache directory.
    Hidden entries are judged on any path part, not only on the file name, so a
    dot-directory is skipped along with its contents.

    Args:
        path: Candidate file, inside ``root``.
        root: Directory being inventoried.

    Returns:
        The reason, or ``None`` when the file is a fixture.
    """
    parts = path.relative_to(root).parts
    for part in parts:
        if part in EXCLUDED_DIRECTORIES:
            return EXCLUDED_DIRECTORIES[part]
    if any(part.startswith(".") for part in parts):
        return "hidden"
    return EXCLUDED_SUFFIXES.get(path.suffix.lower())


def _sha256(path: pathlib.Path) -> str:
    """Return the hexadecimal SHA-256 of ``path``, read in chunks.

    Args:
        path: File to hash.

    Returns:
        Sixty-four hexadecimal characters.
    """
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(_CHUNK_BYTES):
            digest.update(chunk)
    return digest.hexdigest()


def _record(
    path: pathlib.Path,
    root: pathlib.Path,
    detector: Callable[[pathlib.Path], Any] | None,
) -> FixtureRecord:
    """Return the inventory record for one fixture file.

    Args:
        path: Fixture file, inside ``root``.
        root: Directory being inventoried.
        detector: The legacy type detector, or ``None`` when it is not
            importable. ``None`` leaves the ``pdf_type`` key off rather than
            filling it with a guess.

    Returns:
        The record, with ``path`` and ``folder`` relative to ``root``, and
        ``pdf_type`` for a PDF when the detector is available.
    """
    relative = path.relative_to(root)
    record = FixtureRecord(
        path=relative.as_posix(),
        folder=relative.parent.as_posix(),
        name=path.stem,
        extension=path.suffix.lower().lstrip("."),
        bytes=path.stat().st_size,
        sha256=_sha256(path),
    )
    if detector is not None and path.suffix.lower() == _PDF_SUFFIX:
        record["pdf_type"] = _pdf_type(path, detector)
    return record


def _detector() -> Callable[[pathlib.Path], Any] | None:
    """Return ``voucherflow``'s type detector, or ``None`` when unavailable.

        Imported inside the function so the inventory still runs in a checkout that
        has no ``legacy/``, which is the normal case: the package is a legacy
    dependency and is not declared in ``pyproject.toml``.

        Returns:
            The detector callable, or ``None``. The caller decides what an
            undetected PDF means; this function does not substitute a default.
    """
    try:
        # Imported here rather than at module scope so the inventory still runs in
        # a checkout with no ``legacy/``: the detector is a legacy dependency that
        # ``pyproject.toml`` does not declare, so its absence is the normal case.
        from voucherflow.processing.type_detector import (  # pylint: disable=import-outside-toplevel
            detectar,
        )
    except ImportError:  # pragma: no cover - depends on the environment
        return None
    return detectar


def _pdf_type(path: pathlib.Path, detector: Callable[[pathlib.Path], Any]) -> str:
    """Ask the legacy detector whether one PDF is text or a scan.

    The detector decides by counting pages whose ``get_text`` yields something
    besides whitespace, which is why it cannot see a stale *invisible* text
    layer: such a scan is reported ``pdf_texto``. That blindness is the
    detector's, and it is recorded here as the detector's answer rather than
    corrected — an inventory of a legacy answer is only useful if it is the
    legacy answer. The kernel that supersedes it measures the hidden layer.

    Args:
        path: The PDF to detect.
        detector: ``voucherflow``'s ``detectar``.

    Returns:
        One of :data:`PDF_TYPES`.

    Raises:
        ValueError: If the detector answers with anything else. That is a
            vocabulary breach — a PDF detected as an image or as unsupported —
            and recording it as a type would put a value in the manifest that
            the field does not mean.
    """
    answer = detector(path).tipo
    if answer not in PDF_TYPES:
        raise ValueError(f"{path.name}: detector answered {answer!r} for a PDF")
    return answer


def _scan(
    root: pathlib.Path,
    output: pathlib.Path,
    detector: Callable[[pathlib.Path], Any] | None,
) -> tuple[list[FixtureRecord], list[ExcludedPath]]:
    """Split ``root`` into inventoried records and recorded exclusions.

    Args:
        root: Directory being inventoried.
        output: The manifest's own path, resolved; skipped without a record.
        detector: The legacy type detector, or ``None``.

    Returns:
        The records and the exclusions, both in path order.
    """
    entries: list[FixtureRecord] = []
    excluded: list[ExcludedPath] = []
    for path in sorted(root.rglob("*")):
        if path.is_dir() or path.resolve() == output:
            continue
        # A directory the inventory does not cover at all, decided **before** any
        # per-file rule: its contents are not corpus fixtures, so neither a record nor
        # an ``excluded`` entry would be true of them.
        if any(part in EXCLUDED_DIRECTORIES for part in path.relative_to(root).parts):
            continue
        reason = _exclusion_reason(path, root)
        if reason is None:
            entries.append(_record(path, root, detector))
        elif reason in EXCLUDED_SUFFIXES.values():
            excluded.append(
                {"path": path.relative_to(root).as_posix(), "reason": reason}
            )
    return entries, excluded


def _by_folder(entries: list[FixtureRecord]) -> dict[str, dict[str, int]]:
    """Return the file count and byte total of each fixture folder.

    Args:
        entries: The inventoried records.

    Returns:
        One ``{"files": ..., "bytes": ...}`` bucket per folder, folder-sorted.
    """
    folders: dict[str, list[FixtureRecord]] = {}
    for entry in entries:
        folders.setdefault(entry["folder"], []).append(entry)
    return {
        folder: {
            "files": len(group),
            "bytes": sum(item["bytes"] for item in group),
        }
        for folder, group in sorted(folders.items())
    }


def build(root: pathlib.Path, output: pathlib.Path, *, detect: bool = True) -> Manifest:
    """Return the inventory of ``root``, leaving ``output`` out of it.

    Args:
        root: Directory holding the fixture files.
        output: Path the manifest is written to; skipped, so the inventory never
            lists its own output.
        detect: Whether to ask the detector for each PDF's type. ``True`` still
            records no ``pdf_type`` key when ``voucherflow`` is unavailable, so
            this flag says what was *attempted* and ``pdf_detector`` says what
            was *achieved*.

    Returns:
        The manifest, with every count and total derived from ``entries``.
    """
    detector = _detector() if detect else None
    entries, excluded = _scan(root, output.resolve(), detector)
    return {
        "root": pathlib.Path(os.path.relpath(root, _REPO_ROOT)).as_posix(),
        "files": len(entries),
        "bytes": sum(entry["bytes"] for entry in entries),
        "pdf_detector": _DETECTOR if detector is not None else "absent",
        "by_folder": _by_folder(entries),
        "excluded": excluded,
        "entries": entries,
    }


def _type_tally(entries: list[FixtureRecord]) -> str:
    """Summarize the detected PDF types for the run's one-line report.

    Args:
        entries: The inventoried records.

    Returns:
        A ``"pdf_texto=17 pdf_escaneado=5"`` style tally, or ``"undetected"``
        when no PDF was detected. Reading it back from the records is what keeps
        the summary and the file from disagreeing.
    """
    tally: dict[str, int] = {}
    for entry in entries:
        answer = entry.get("pdf_type")
        if answer is not None:
            tally[answer] = tally.get(answer, 0) + 1
    if not tally:
        return "undetected"
    return " ".join(f"{answer}={tally[answer]}" for answer in sorted(tally))


def main(argv: list[str] | None = None) -> int:
    """Write the manifest and print a one-line summary.

    Args:
        argv: Command-line arguments; ``None`` reads ``sys.argv``.

    Returns:
        The process exit code: ``0`` on success.
    """
    parser = argparse.ArgumentParser(description="Inventory the fixture files.")
    parser.add_argument("--root", type=pathlib.Path, default=_HERE)
    parser.add_argument("--out", type=pathlib.Path, default=_HERE / "manifest.json")
    parser.add_argument(
        "--no-pdf-types",
        action="store_true",
        help="skip PDF type detection, leaving the inventory to the stdlib",
    )
    args = parser.parse_args(argv)
    manifest = build(args.root, args.out, detect=not args.no_pdf_types)
    args.out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(
        f"{args.out}: {manifest['files']} files, {manifest['bytes']} bytes, "
        f"{len(manifest['excluded'])} excluded, "
        f"detector={manifest['pdf_detector']}, {_type_tally(manifest['entries'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
